Add Gianluca's details to index.html
alan-turing-institute/2017-phd-students pull request #17
Opened 2017-09-29 10:53 UTC by gianlucadetommaso

My academic background

2017-09-29 10:54 UTC, ghost reviewed
Ciao Gianluca, this looks good. Can you specify if you are a PhD Student or an Enrichment Student by deleting one of them?

2017-09-29 11:06 UTC, tahaceritli submitted a review, later dismissed

2017-09-29 11:06 UTC, martintoreilly commented
@gianlucadetommaso Please can you make the change @migliris suggested and pick either Doctoral or Enrichment student in the "title" section? Thanks,.

2017-09-29 11:07 UTC, amartya18x requested changes

2017-09-29 11:07 UTC, amartya18x commented on index.html
>          <p class="title">PhD student or Enrichment student</p>
@gianlucadetommaso  I think this is where you should mention that.

2017-10-12 22:07 UTC, martintoreilly commented
Made requested change and tested locally so merging

2017-10-12 22:07 UTC, merged